# docker-compose.test.yml
services:
  bootstrap:
    build: .
    command: ["--addr=:6882", "--bootstrap", "--id-seed=bootstrap-1"]
    healthcheck:
      test: ["CMD-SHELL", "echo -n PING | nc -u -w 1 127.0.0.1 6882 | grep -q ^PONG"]
      interval: 2s
      timeout: 1s
      retries: 10

  node:
    build: .
    command: ["--addr=:6882", "--peers=bootstrap:6882"]
    depends_on: [bootstrap]
    healthcheck:
      test: ["CMD-SHELL", "echo -n PING | nc -u -w 1 127.0.0.1 6882 | grep -q ^PONG"]
      interval: 2s
      timeout: 1s
      retries: 10

  tester:
    image: alpine:3.20
    depends_on:
      - bootstrap
      - node
    environment:
      NODE_SERVICE: node
      NODE_PORT: "6882"
      BOOTSTRAP_HOST: bootstrap
      BOOTSTRAP_PORT: "6882"
      MAX_INDEX: "300"  
      TIMEOUT: "1"       # nc timeout seconds
    volumes:
      - ./tests/test-ping.sh:/test-ping.sh:ro
    entrypoint: ["/bin/sh", "/test-ping.sh"]
